default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: cvillized_development

test:
  <<: *default
  database: cvillized_test

production:
  <<: *default
  database: cvillized_production
